### ISSUE TITLE
[FRQ] Display lobster market price and current balance on separate axes

### ISSUE THREAD

**Issue by 22a** [shawa/lobsters.trade#1]
# Feature request
 Hello [bloomberg dashboard maintainer](https://github.com/shawa), please split the graph out - displaying the two realtime datasets in their own independently scaled axes.

It is difficult for me to spot small changes in lobster market when my balance is large - I expect this to become even more of an issue as I expand my empire. Please.

  <img width="561" alt="Annotation 2020-04-05 223018" src="https://user-images.githubusercontent.com/7144173/78510496-5fd35180-778d-11ea-9efd-41113b60c9d4.png">

**Comment by houli** [comment]
I wish to go to the moon. Such a bloomberg dashboard is insufficient to take me there.

**Comment by 22a** [comment]
Hey, just a quick check in on this to see if you've made any progress on fixing this or if you think you'll be able to prioritise this work. Please. It has become a much more pertinent issue now that I am richer.

<img width="527" alt="Annotation 2020-04-05 223925" src="https://user-images.githubusercontent.com/7144173/78510603-6615fd80-778e-11ea-88ff-1445bf2c8f55.png">

Please act quick or I may make a foolish decision.
